from pydantic import BaseModel, Field


class CompanyAnalysis(BaseModel):
    """
    Structured company analysis generated by the AI model.
    """

    company_overview: str = Field(
        description="General overview of the company"
    )

    business_model_insights: list[str] = Field(
        description="Insights about the company's business model"
    )

    market_trends: list[str] = Field(
        description="Important market and industry trends"
    )

    technology_insights: list[str] = Field(
        description="Technology and AI-related insights"
    )

    key_observations: list[str] = Field(
        description="Important observations about the company"
    )